// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTjNAnbxqRVT99MoUhTXkUXaHsA7bx0Fw',
    appId: '1:342531348832:web:cd22eda602fd1cc2982605',
    messagingSenderId: '342531348832',
    projectId: 'anime-quiz-1ab1b',
    authDomain: 'anime-quiz-1ab1b.firebaseapp.com',
    storageBucket: 'anime-quiz-1ab1b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9E0pfoXBS5VM4FwUM9ZMlU0V2ensJmFo',
    appId: '1:342531348832:android:07a8c184f69401d8982605',
    messagingSenderId: '342531348832',
    projectId: 'anime-quiz-1ab1b',
    storageBucket: 'anime-quiz-1ab1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjcPaKG1_BIU0Ssos7Ufqy_0tDRpQWHeU',
    appId: '1:342531348832:ios:ef6e33cd4df9673b982605',
    messagingSenderId: '342531348832',
    projectId: 'anime-quiz-1ab1b',
    storageBucket: 'anime-quiz-1ab1b.firebasestorage.app',
    iosBundleId: 'com.example.quiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTjNAnbxqRVT99MoUhTXkUXaHsA7bx0Fw',
    appId: '1:342531348832:web:20be10967a8942ae982605',
    messagingSenderId: '342531348832',
    projectId: 'anime-quiz-1ab1b',
    authDomain: 'anime-quiz-1ab1b.firebaseapp.com',
    storageBucket: 'anime-quiz-1ab1b.firebasestorage.app',
  );
}