name: Build iOS IPA
on:
  workflow_dispatch:
jobs:
  build-ios:
    name: Build iOS IPA
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Disable Swift Package Manager
        run: flutter config --no-enable-swift-package-manager
      - name: Install dependencies
        run: flutter pub upgrade
      - name: Upgrade connectivity_plus
        run: flutter pub upgrade connectivity_plus
      - name: Set iOS deployment target to 15.0
        run: |
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]*/IPHONEOS_DEPLOYMENT_TARGET = 15.0/g' ios/Runner.xcodeproj/project.pbxproj
      - name: Build iOS (no code sign)
        run: flutter build ios --release --no-codesign
      - name: Package into IPA
        run: |
          mkdir Payload
          mv Runner.app/ Payload/
          zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos
      - name: Upload IPA as artifact
        uses: actions/upload-artifact@v4
        with:
          name: FlutterIpaExport
          path: build/ios/iphoneos/FlutterIpaExport.ipa
